### ISSUE TITLE
Epic: Fix Server TCK tests

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-azure#439]
We had to [temporarally disable a lot of TCK server tests to get the test to pass](https://github.com/micronaut-projects/micronaut-azure/pull/437/files#diff-30ada62f53697202ed68fb75991c2bde9da85609519cdacd7e8611e3b3552c9f)

These need to be investigated and fixed or explained prior to Micronaut 4.0.0

#### Immutable request object issues

- [ ] io.micronaut.http.server.tck.tests.filter.ResponseFilterTest
- [ ] io.micronaut.http.server.tck.tests.filter.RequestFilterExceptionHandlerTest
- [ ] io.micronaut.http.server.tck.tests.filter.RequestFilterTest

#### Route matching

- [ ] io.micronaut.http.server.tck.tests.VersionTest
- [ ] io.micronaut.http.server.tck.tests.MiscTest

#### 'Error'

- [ ] io.micronaut.http.server.tck.tests.FiltersTest
- [ ] io.micronaut.http.server.tck.tests.DeleteWithoutBodyTest
- [ ] io.micronaut.http.server.tck.tests.CookiesTest

#### Encoding

- [ ] io.micronaut.http.server.tck.tests.OctetTest

#### Headers

- [ ] io.micronaut.http.server.tck.tests.ErrorHandlerTest

#### Reactive

- [ ] io.micronaut.http.server.tck.tests.BodyTest -- testCustomListBodyPOJOReactiveTypes fails

#### Misc/Unknown

- [ ] io.micronaut.http.server.tck.tests.cors.CorsSimpleRequestTest -- no port for the server under test
- [ ] io.micronaut.http.server.tck.tests.ParameterTest
- [ ] io.micronaut.http.server.tck.tests.filter.ClientRequestFilterTest
- [ ] io.micronaut.http.server.tck.tests.FluxTest
- [ ] io.micronaut.http.server.tck.tests.cors.SimpleRequestWithCorsNotEnabledTest
- [ ] io.micronaut.http.server.tck.tests.FilterErrorTest
- [ ] io.micronaut.http.server.tck.tests.filter.ClientResponseFilterTest
